# CNPG PostgreSQL cluster for SwingAgent
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: swing-postgres
  namespace: default
  labels:
    app: swing-agent
    component: database
spec:
  instances: 3
  
  postgresql:
    parameters:
      # Connection settings
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      
      # Performance settings
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      
      # Logging
      log_statement: "mod"
      log_min_duration_statement: "1000"
    
    pg_hba:
      - "host all all 0.0.0.0/0 md5"
  
  bootstrap:
    initdb:
      database: swing_agent
      owner: swing_user
      secret:
        name: swing-postgres-credentials
      options:
        - "--encoding=UTF8"
        - "--locale=C"
        - "--data-checksums"
  
  storage:
    size: 20Gi
    storageClass: fast-ssd  # Adjust to your storage class
  
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  
  monitoring:
    enabled: true
    customQueriesConfigMap:
      - name: swing-postgres-queries
        key: queries.yaml
  
  # High availability configuration
  primaryUpdateStrategy: unsupervised
  
  # Backup configuration
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://your-backup-bucket/swing-postgres"
      s3Credentials:
        accessKeyId:
          name: backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-credentials
          key: SECRET_ACCESS_KEY
        region:
          name: backup-credentials
          key: REGION
      wal:
        retention: "7d"
        maxParallel: 8
      data:
        retention: "30d"
        immediateCheckpoint: true
        jobs: 2
  
  # Affinity rules to spread across nodes
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              cnpg.io/cluster: swing-postgres
          topologyKey: kubernetes.io/hostname